name: concept
channels:
  - pytorch
  - nvidia
  - conda-forge # necessary to be above defaults
  - defaults
dependencies:
  - python=3.10
  - pip=24.0
  - numpy=1.26
  - pandas=2.2
  - matplotlib=3.8
  - scikit-learn=1.4
  - scipy=1.12
# - jupyterlab=4.1
  - pytorch=2.2
  - torchvision=0.17
  - pytorch-cuda=12.1
  - lightning=2.2
  - dask
  - scanpy=1.9
  - python-igraph
  - leidenalg
  - tensorboard
  - hydra-core=1.3
  - biopython
  - wandb=0.16

# install flash attention as in https://github.com/Dao-AILab/flash-attention