
# Project directory structure:
# PROJECT_PATH/
# ├── data/
# │   └── <dataset_name>/
# │       ├── pc_gene_token_mapping.pkl
# │       └── h5ads/
# │           ├── <adata_1>.h5ad
# │           ├── <adata_2>.h5ad
# │           └── ...
# ├── model_checkpoints/
# └── panels/
# |   └── <panel_name>/
# |       ├── panel_1.csv
# |       ├── panel_2.csv
# |       └── ...
# └── references/
# |   └── embeddings/
# |       └── <embedding_name>/
# |           └── <human_gene_embeddings>.csv
# |           └── <mouse_gene_embeddings>.csv
# |           └── ...
# |   └── vocabulary/
# |       └── <gene_token_mapping_16_species>.csv

defaults:
  - model: ContrastiveModel
  - datamodule: DataModuleBasic
  - _self_

wandb:
  enabled: False
  run_name: null # Required if enabled=True
  entity: null  # Required if enabled=True
  project: null  # Required if enabled=True

initialize:  
  resume: False
  run_id: null
  checkpoint: null
  create_new_run: False

profiler:
  enabled: False # Use profiler only for debugging
  
PATH:
  PROJECT_PATH: ???
  LOCAL_DIR: null # A fast local directory to copy datasets to for faster training
  CHECKPOINT_ROOT: ${PATH.PROJECT_PATH}/model_checkpoints
  PANELS_PATH: ${PATH.PROJECT_PATH}/panels
  GENE_MAPPING_PATH: ${PATH.PROJECT_PATH}/references/vocabulary/gene_token_mapping_16_species.csv
  PRETRAINED_VOCABULARY: ${PATH.PROJECT_PATH}/references/embeddings/esm2_t30


