defaults:
  - split_cellxgene_hsapiens: split_cellxgene_hsapiens_2025_11_08_primary
  - split_cellxgene_mmusculus: split_cellxgene_mmusculus_2025_11_08_primary
  - split_cellxgene_cjacchus: split_cellxgene_cjacchus_2025_11_08_primary
  - split_cellxgene_mmulatta: split_cellxgene_mmulatta_2025_11_08_primary
  - split_cellxgene_ptroglodytes: split_cellxgene_ptroglodytes_2025_11_08_primary

  - split_scbasecount_hsapiens: split_scbasecount_hsapiens_2025_02_25
  - split_scbasecount_mmusculus: split_scbasecount_mmusculus_2025_02_25
  - split_scbasecount_mmulatta: split_scbasecount_mmulatta_2025_02_25
  - split_scbasecount_cjacchus: split_scbasecount_cjacchus_2025_02_25
  - split_scbasecount_ptroglodytes: split_scbasecount_ptroglodytes_2025_02_25
  - split_scbasecount_btaurus: split_scbasecount_btaurus_2025_02_25
  - split_scbasecount_celegans: split_scbasecount_celegans_2025_02_25
  - split_scbasecount_drerio: split_scbasecount_drerio_2025_02_25
  - split_scbasecount_dmelanogaster: split_scbasecount_dmelanogaster_2025_02_25
  - split_scbasecount_ecaballus: split_scbasecount_ecaballus_2025_02_25
  - split_scbasecount_ggallus: split_scbasecount_ggallus_2025_02_25
  - split_scbasecount_ggorilla: split_scbasecount_ggorilla_2025_02_25
  - split_scbasecount_hgfemale: split_scbasecount_hgfemale_2025_02_25
  - split_scbasecount_ocuniculus: split_scbasecount_ocuniculus_2025_02_25
  - split_scbasecount_oaries: split_scbasecount_oaries_2025_02_25
  - split_scbasecount_sscrofa: split_scbasecount_sscrofa_2025_02_25

name: DataModule
species:
  - hsapiens
  - mmusculus
  - cjacchus
  - mmulatta
  - ptroglodytes
  - btaurus
  - celegans
  - drerio
  - dmelanogaster
  - ecaballus
  - ggallus
  - ggorilla
  - hgfemale
  - ocuniculus
  - oaries
  - sscrofa
obs_keys: ["dataset", "donor_id", "tissue", "cell_type"]
normalization: raw
gene_sampling_strategy: top-nonzero
model_speed_sanity_check: False
precomp_embs_key: null
dataset:
  train:
    split: 
      - ${datamodule.split_cellxgene_hsapiens}
      - ${datamodule.split_cellxgene_mmusculus}
      - ${datamodule.split_cellxgene_cjacchus}
      - ${datamodule.split_cellxgene_mmulatta}
      - ${datamodule.split_cellxgene_ptroglodytes}
      - ${datamodule.split_scbasecount_hsapiens}
      - ${datamodule.split_scbasecount_mmusculus}
      - ${datamodule.split_scbasecount_mmulatta}
      - ${datamodule.split_scbasecount_cjacchus}
      - ${datamodule.split_scbasecount_ptroglodytes}
      - ${datamodule.split_scbasecount_btaurus}
      - ${datamodule.split_scbasecount_celegans}
      - ${datamodule.split_scbasecount_drerio}
      - ${datamodule.split_scbasecount_dmelanogaster}
      - ${datamodule.split_scbasecount_ecaballus}
      - ${datamodule.split_scbasecount_ggallus}
      - ${datamodule.split_scbasecount_ggorilla}
      - ${datamodule.split_scbasecount_hgfemale}
      - ${datamodule.split_scbasecount_ocuniculus}
      - ${datamodule.split_scbasecount_oaries}
      - ${datamodule.split_scbasecount_sscrofa}
    max_tokens: 1000
    panel_overlap: False
    panel_selection: mixed
    panel_selection_mixed_prob: 0.25
    panel_filter_regex: ".*"
    panel_size_min: 400
    panel_size_max: 60000
    panel_max_drop_rate: 0.5
    feature_max_drop_rate: null
    qc_threshold: null
    max_total_seq_length: null
  val:
    same_as_train:
      split: 
        - ${datamodule.split_cellxgene_hsapiens}
      panel_overlap: ${datamodule.dataset.train.panel_overlap}
      panel_selection: ${datamodule.dataset.train.panel_selection}
      panel_selection_mixed_prob: ${datamodule.dataset.train.panel_selection_mixed_prob}
      panel_filter_regex: ${datamodule.dataset.train.panel_filter_regex}
      panel_size_min: ${datamodule.dataset.train.panel_size_min}
      panel_size_max: ${datamodule.dataset.train.panel_size_max}
    within_P200_B256:
      split: 
        - ${datamodule.split_cellxgene_hsapiens}
      panel_selection: random
      panel_size_min: 200
      panel_size_max: 200
    within_P800_B256:
      split: 
        - ${datamodule.split_cellxgene_hsapiens}
      panel_selection: random
      panel_size_min: 800
      panel_size_max: 800
    within_P6400_B256:
      split: 
        - ${datamodule.split_cellxgene_hsapiens}
      panel_selection: random
      panel_size_min: 6400
      panel_size_max: 6400
    within_unbalanced_B256:
      split: 
        - ${datamodule.split_cellxgene_hsapiens}
      panel_selection: random
      panel_size_min: 15000
      panel_size_max: 15000
    within_Preselected_vs_all_B256:
      split: 
        - ${datamodule.split_cellxgene_hsapiens}
      panel_selection: preselected
      panel_filter_regex: ".*"
      panel_size_min: 100000
      panel_size_max: 100000
    within_Preselected_vs_all_overlap_B256:
      split: 
        - ${datamodule.split_cellxgene_hsapiens}
      panel_selection: preselected
      panel_filter_regex: ".*"
      panel_size_min: 100000
      panel_size_max: 100000
      panel_overlap: True
    within_P6400_B256_mmusculus:
      split: 
        - ${datamodule.split_cellxgene_mmusculus}
      panel_selection: random
      panel_size_min: 6400
      panel_size_max: 6400
    within_P6400_B256_other_species:
      split: 
        - ${datamodule.split_cellxgene_cjacchus}
        - ${datamodule.split_cellxgene_mmulatta}
        - ${datamodule.split_cellxgene_ptroglodytes}
      panel_selection: random
      panel_size_min: 6400
      panel_size_max: 6400
    within_tissue_P6400_B256:
      split: 
        - source: ${datamodule.split_cellxgene_hsapiens}
          key: train
      panel_selection: random
      panel_size_min: 6400
      panel_size_max: 6400
    within_donor_P6400_B256:
      split: 
        - ${datamodule.split_cellxgene_hsapiens}
      panel_selection: random
      panel_size_min: 6400
      panel_size_max: 6400


dataloader:
  train:
    within_group_sampling: "dataset"
    batch_size: 128
    shuffle: True
    num_workers: 14
    pin_memory: True
    drop_last: True
    num_samples: null
    num_groups: null
  val:
    same_as_train:
      within_group_sampling: ${datamodule.dataloader.train.within_group_sampling}
      batch_size: ${datamodule.dataloader.train.batch_size}
      shuffle: ${datamodule.dataloader.train.shuffle}
      num_workers: 2
      pin_memory: False
      drop_last: ${datamodule.dataloader.train.drop_last}
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True
    within_P200_B256:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True
    within_P800_B256:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True
    within_P6400_B256:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True
    within_unbalanced_B256:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True
    within_Preselected_vs_all_B256:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True
    within_Preselected_vs_all_overlap_B256:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True
    within_P6400_B256_mmusculus:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True
    within_P6400_B256_other_species:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True
    within_tissue_P6400_B256:
      within_group_sampling: "tissue"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True
    within_donor_P6400_B256:
      within_group_sampling: ["dataset", "donor_id"]
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
      num_groups: null
      sample_groups_equally: True